INSERT INTO USERS (ID, NAME, PASSWORD, ROLE, ENABLED) VALUES (1, 'Anabel', '{bcrypt}$2b$12$FmOzLA/SRVrHvDlSFdiiOeXDC5PvD0FOMAqN7KqoCr4fYLjB9AWYW', 'USER', 1);
INSERT INTO USERS (ID, NAME, PASSWORD, ROLE, ENABLED) VALUES (2, 'Bautista', '{bcrypt}$2b$12$Ili5TONrOqpJ7rBWQCUVYO20Ta3m85mEKltR5nByyo2ectZh4zcDq', 'ADMIN', 1);
INSERT INTO USERS (ID, NAME, PASSWORD, ROLE, ENABLED) VALUES (3, 'Carlos', '{bcrypt}$2b$12$2.hzsH4zDFMGgN6utPf5C.XDaHlvyGGAX/Pi2Bci2QjQo2htKV5nu', 'USER', 1);
